const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite'); const {Pool}=require('pg');
const port=Number(process.env.PORT||3000),host=process.env.HOST||'0.0.0.0',root=__dirname,adminEmail=(process.env.ADMIN_EMAIL||'admin@souqna.local').toLowerCase(),usePostgres=Boolean(process.env.DATABASE_URL),firebaseApiKey=process.env.FIREBASE_API_KEY||'AIzaSyCKgJr981P09i3hiMyRTDgL_67_Q1R671Q';
const pool=usePostgres?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:undefined}):null;
const sqlite=usePostgres?null:new DatabaseSync(path.join(root,'souqna.sqlite'));
const schema=`CREATE TABLE IF NOT EXISTS listings(id BIGSERIAL PRIMARY KEY,seller_id BIGINT,title TEXT NOT NULL,category TEXT NOT NULL,condition TEXT NOT NULL,price NUMERIC(12,2) NOT NULL CHECK(price>=0),city TEXT NOT NULL,description TEXT NOT NULL,emoji TEXT NOT NULL DEFAULT '📦',images TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,verified INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL);CREATE TABLE IF NOT EXISTS messages(id BIGSERIAL PRIMARY KEY,listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,body TEXT NOT NULL CHECK(length(body) BETWEEN 1 AND 2000),created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS reports(id BIGSERIAL PRIMARY KEY,listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,reporter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,reason TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(listing_id,reporter_id));CREATE TABLE IF NOT EXISTS reviews(id BIGSERIAL PRIMARY KEY,listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,seller_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,reviewer_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),body TEXT NOT NULL CHECK(length(body) BETWEEN 3 AND 500),created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(listing_id,reviewer_id));`;
if(!usePostgres){sqlite.exec(schema.replaceAll('BIGSERIAL','INTEGER').replaceAll('TIMESTAMPTZ','TEXT').replaceAll('CURRENT_TIMESTAMP','CURRENT_TIMESTAMP'));}
function ph(q){let n=0,quote=null,out='';for(let i=0;i<q.length;i++){let c=q[i];if(quote){out+=c;if(c===quote){if(q[i+1]===quote){out+=q[++i]}else quote=null}else if(c==='\\')out+=q[++i]}else if(c==="'"||c==='"'){quote=c;out+=c}else if(c==='?')out+=`$${++n}`;else out+=c}return out}
async function all(q,p=[]){return usePostgres?(await pool.query(ph(q),p)).rows:sqlite.prepare(q).all(...p)} async function get(q,p=[]){return usePostgres?(await pool.query(ph(q),p)).rows[0]:sqlite.prepare(q).get(...p)}
async function run(q,p=[]){if(usePostgres){let r=await pool.query(ph(q),p);return {lastInsertRowid:r.rows[0]?.id,changes:r.rowCount}}return sqlite.prepare(q).run(...p)}
function json(r,s,b){r.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});r.end(JSON.stringify(b))} function body(req){return new Promise((res,rej)=>{let x='';req.on('data',c=>x+=c).on('end',()=>{try{res(JSON.parse(x||'{}'))}catch{rej(Error('Invalid JSON'))}}).on('error',rej)})} function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{let i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1).trim())]}))}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return `${s}:${crypto.scryptSync(p,s,64).toString('hex')}`} function verify(p,v){let [s,e]=String(v).split(':');if(!s||!e)return false;let a=crypto.scryptSync(p,s,64);let b=Buffer.from(e,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)} async function user(req){let t=cookies(req).souqna_session;if(!t)return null;return get("SELECT users.id,users.email FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND sessions.expires_at>CURRENT_TIMESTAMP",[crypto.createHash('sha256').update(t).digest('hex')])} function admin(u){return!!u&&u.email.toLowerCase()===adminEmail} async function session(res,id){let t=crypto.randomBytes(32).toString('hex'),expiry=usePostgres?"CURRENT_TIMESTAMP + INTERVAL '30 days'":"datetime('now', '+30 days')";await run(`INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,${expiry})`,[crypto.createHash('sha256').update(t).digest('hex'),id]);res.setHeader('Set-Cookie',`souqna_session=${encodeURIComponent(t)}; HttpOnly; SameSite=Lax; ${process.env.NODE_ENV==='production'?'Secure; ':''}Path=/; Max-Age=2592000`)}
const loginAttempts=new Map();
function allowLogin(req,email){const key=`${req.socket.remoteAddress||'unknown'}:${email}`,now=Date.now(),recent=(loginAttempts.get(key)||[]).filter(time=>now-time<15*60*1000);if(recent.length>=10){loginAttempts.set(key,recent);return false}recent.push(now);loginAttempts.set(key,recent);return true}
function listing(r){let images=[];try{images=JSON.parse(r.images||'[]')}catch{}return {id:r.id,title:r.title,category:r.category,condition:r.condition,price:r.price,city:r.city,description:r.description,emoji:r.emoji,images:Array.isArray(images)?images:[],status:r.status,sellerId:r.seller_id,createdAt:r.created_at}}
const server=http.createServer(async(req,res)=>{let u=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(req.method==='GET'&&u.pathname==='/api/health'){if(usePostgres)await pool.query('SELECT 1');return json(res,200,{ok:true,database:usePostgres?'postgresql':'sqlite',timestamp:new Date().toISOString()})}if(req.method==='GET'&&u.pathname==='/api/auth/me'){let x=await user(req);return json(res,200,{user:x?{...x,isAdmin:admin(x)}:null})}
if(req.method==='POST'&&u.pathname==='/api/auth/firebase'){let b=await body(req),idToken=typeof b.idToken==='string'?b.idToken.trim():'';if(!idToken||idToken.length>5000)return json(res,400,{error:'تعذر قراءة جلسة Google'});let verification;try{let response=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${encodeURIComponent(firebaseApiKey)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken})});verification=await response.json();if(!response.ok||!Array.isArray(verification.users)||!verification.users[0])return json(res,401,{error:'انتهت صلاحية جلسة Google. سجّل الدخول مجددًا.'})}catch(e){console.error('Firebase token verification failed:',e);return json(res,503,{error:'تعذر التحقق من حساب Google حاليًا. حاول مجددًا.'})}let profile=verification.users[0],email=typeof profile.email==='string'?profile.email.trim().toLowerCase():'';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json(res,401,{error:'حساب Google لا يحتوي على بريد إلكتروني صالح'});let existing=await get('SELECT id,email FROM users WHERE email=?',[email]);let id=existing?.id;if(!id){let created=await run('INSERT INTO users(email,password_hash,verified) VALUES(?,?,?) RETURNING id',[email,hash(crypto.randomBytes(32).toString('hex')),1]);id=created.lastInsertRowid}else await run('UPDATE users SET verified=1 WHERE id=?',[id]);await session(res,id);return json(res,200,{user:{id,email,isAdmin:email===adminEmail}})}
if(req.method==='POST'&&u.pathname==='/api/auth/login'&&!allowLogin(req,'all'))return json(res,429,{error:'محاولات تسجيل الدخول كثيرة. انتظر 15 دقيقة ثم حاول مجددًا.'});
if(req.method==='POST'&&(u.pathname==='/api/auth/register'||u.pathname==='/api/auth/login')){let b=await body(req),email=typeof b.email==='string'?b.email.trim().toLowerCase():'',pw=typeof b.password==='string'?b.password:'';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json(res,400,{error:'أدخل بريدًا إلكترونيًا صحيحًا مثل name@example.com'});if(pw.length<8||pw.length>128)return json(res,400,{error:'كلمة المرور يجب أن تكون بين 8 و128 حرفًا'});if(u.pathname.endsWith('register')){try{let x=await run('INSERT INTO users(email,password_hash) VALUES(?,?) RETURNING id',[email,hash(pw)]);await session(res,x.lastInsertRowid);return json(res,201,{user:{id:x.lastInsertRowid,email:x.email||email}})}catch(e){if(String(e.message).toLowerCase().includes('unique'))return json(res,409,{error:'هذا البريد الإلكتروني مسجل مسبقًا'});throw e}}let x=await get('SELECT id,email,password_hash FROM users WHERE email=?',[email]);if(!x||!verify(pw,x.password_hash))return json(res,401,{error:'البريد الإلكتروني أو كلمة المرور غير صحيحة'});await session(res,x.id);return json(res,200,{user:{id:x.id,email:x.email}})}
if(req.method==='POST'&&u.pathname==='/api/auth/register'||req.method==='POST'&&u.pathname==='/api/auth/login'){let b=await body(req),email=typeof b.email==='string'?b.email.trim().toLowerCase():'',pw=typeof b.password==='string'?b.password:'';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||pw.length<8||pw.length>128)return json(res,400,{error:'?????? ???????? ??? ?????'});if(u.pathname.endsWith('register')){try{let x=await run('INSERT INTO users(email,password_hash) VALUES(?,?) RETURNING id',[email,hash(pw)]);await session(res,x.lastInsertRowid);return json(res,201,{user:{id:x.lastInsertRowid,email}})}catch(e){if(String(e.message).includes('unique'))return json(res,409,{error:'??? ?????? ???? ??????'});throw e}}let x=await get('SELECT id,email,password_hash FROM users WHERE email=?',[email]);if(!x||!verify(pw,x.password_hash))return json(res,401,{error:'?????? ?? ???? ?????? ??? ?????'});await session(res,x.id);return json(res,200,{user:{id:x.id,email:x.email}})}
if(req.method==='POST'&&u.pathname==='/api/auth/logout'){let t=cookies(req).souqna_session;if(t)await run('DELETE FROM sessions WHERE token_hash=?',[crypto.createHash('sha256').update(t).digest('hex')]);res.setHeader('Set-Cookie','souqna_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return json(res,200,{ok:true})}
if(req.method==='GET'&&u.pathname==='/api/listings')return json(res,200,(await all('SELECT * FROM listings WHERE status=? ORDER BY created_at DESC,id DESC',['active'])).map(listing));let me=await user(req);
if(req.method==='GET'&&u.pathname==='/api/my-listings'){if(!me)return json(res,401,{error:'??? ????? ?????? ?????'});return json(res,200,(await all('SELECT * FROM listings WHERE seller_id=? ORDER BY created_at DESC,id DESC',[me.id])).map(listing))}
if(req.method==='POST'&&u.pathname==='/api/listings'){if(!me)return json(res,401,{error:'يجب تسجيل الدخول أولًا'});let b=await body(req),p=Number(b.price),images=Array.isArray(b.images)?b.images:[];if(typeof b.title!=='string'||b.title.trim().length<3||b.title.trim().length>70||!b.category||!b.condition||!b.city||!Number.isFinite(p)||p<0||typeof b.description!=='string'||b.description.trim().length<3||b.description.trim().length>3000)return json(res,400,{error:'تحقق من بيانات الإعلان'});if(images.length>5||images.some(x=>typeof x!=='string'||!/^data:image\/(jpeg|png|webp);base64,/.test(x))||JSON.stringify(images).length>8*1024*1024)return json(res,400,{error:'يمكن إضافة 5 صور كحد أقصى، وبحجم إجمالي 8 ميجابايت'});let x=await run('INSERT INTO listings(seller_id,title,category,condition,price,city,description,emoji,images) VALUES(?,?,?,?,?,?,?,?,?) RETURNING id',[me.id,b.title.trim(),b.category.trim(),b.condition.trim(),p,b.city.trim(),b.description.trim(),'📦',JSON.stringify(images)]);return json(res,201,listing(await get('SELECT * FROM listings WHERE id=?',[x.lastInsertRowid])))}
if(req.method==='GET'&&u.pathname==='/api/reviews'){let id=Number(u.searchParams.get('listingId'));return json(res,200,await all('SELECT reviews.rating,reviews.body,reviews.created_at,users.email FROM reviews JOIN users ON users.id=reviews.reviewer_id WHERE listing_id=? ORDER BY reviews.created_at DESC',[id]))}
if(req.method==='GET'&&u.pathname==='/api/messages'){if(!me)return json(res,401,{error:'??? ????? ?????? ?????? ???????'});let id=Number(u.searchParams.get('listingId')),rows=await all('SELECT messages.id,messages.body,messages.created_at,users.email FROM messages JOIN users ON users.id=messages.sender_id JOIN listings ON listings.id=messages.listing_id WHERE listing_id=? AND(sender_id=? OR ?=listings.seller_id) ORDER BY messages.created_at ASC,messages.id ASC',[id,me.id,me.id]);return json(res,200,rows.map(x=>({id:x.id,body:x.body,email:x.email,createdAt:x.created_at})))}
if(req.method==='POST'&&u.pathname==='/api/messages'){if(!me)return json(res,401,{error:'??? ????? ?????? ?????'});let b=await body(req),id=Number(b.listingId),text=typeof b.body==='string'?b.body.trim():'',l=await get('SELECT seller_id FROM listings WHERE id=? AND status=?',[id,'active']);if(!l)return json(res,404,{error:'??????? ??? ????? ?? ??? ???'});if(l.seller_id===me.id)return json(res,400,{error:'?? ????? ?????? ????'});if(text.length<1||text.length>2000)return json(res,400,{error:'??????? ??? ?????'});let x=await run('INSERT INTO messages(listing_id,sender_id,body) VALUES(?,?,?) RETURNING id',[id,me.id,text]);return json(res,201,{id:x.lastInsertRowid,body:text,email:me.email})}
if(req.method==='GET'&&u.pathname==='/api/admin/reports'){if(!admin(me))return json(res,403,{error:'?????? ??????? ??????'});return json(res,200,await all('SELECT reports.id,reports.reason,reports.created_at,listings.id AS listing_id,listings.title,listings.status,reporters.email AS reporter_email FROM reports JOIN listings ON listings.id=reports.listing_id JOIN users reporters ON reporters.id=reports.reporter_id ORDER BY reports.created_at DESC,reports.id DESC'))}
if(req.method==='PATCH'&&u.pathname==='/api/admin/listings'){if(!admin(me))return json(res,403,{error:'?????? ??????? ??????'});let b=await body(req),status=['active','hidden','sold'].includes(b.status)?b.status:null;if(!Number.isInteger(Number(b.listingId))||!status)return json(res,400,{error:'?????? ??????? ??? ?????'});await run('UPDATE listings SET status=? WHERE id=?',[status,Number(b.listingId)]);return json(res,200,{ok:true})}
if(req.method==='PATCH'&&u.pathname==='/api/admin/users'){if(!admin(me))return json(res,403,{error:'?????? ??????? ??????'});let b=await body(req);await run('UPDATE users SET verified=? WHERE id=?',[b.verified?1:0,Number(b.userId)]);return json(res,200,{ok:true})}
if(req.method==='POST'&&u.pathname==='/api/reports'){if(!me)return json(res,401,{error:'??? ????? ?????? ???????'});let b=await body(req),reason=typeof b.reason==='string'?b.reason.trim():'';if(!Number.isInteger(Number(b.listingId))||reason.length<3||reason.length>300)return json(res,400,{error:'?????? ?????? ??? ?????'});try{await run('INSERT INTO reports(listing_id,reporter_id,reason) VALUES(?,?,?)',[Number(b.listingId),me.id,reason])}catch(e){if(String(e.message).includes('unique'))return json(res,409,{error:'??? ?? ????? ?? ??? ???????'});throw e}return json(res,201,{ok:true})}
if(req.method==='POST'&&u.pathname==='/api/reviews'){if(!me)return json(res,401,{error:'??? ????? ?????? ???????'});let b=await body(req),rating=Number(b.rating),reviewBody=typeof b.body==='string'?b.body.trim():'',l=await get('SELECT seller_id FROM listings WHERE id=?',[Number(b.listingId)]);if(!l)return json(res,404,{error:'??????? ??? ?????'});if(l.seller_id===me.id)return json(res,400,{error:'?? ????? ????? ??????'});if(!Number.isInteger(rating)||rating<1||rating>5||reviewBody.length<3||reviewBody.length>500)return json(res,400,{error:'?????? ??????? ??? ?????'});try{await run('INSERT INTO reviews(listing_id,seller_id,reviewer_id,rating,body) VALUES(?,?,?,?,?)',[Number(b.listingId),l.seller_id,me.id,rating,reviewBody])}catch(e){if(String(e.message).includes('unique'))return json(res,409,{error:'??? ?? ????? ??? ???????'});throw e}return json(res,201,{ok:true})}
let m=u.pathname.match(/^\/api\/listings\/(\d+)$/);if(m&&(req.method==='PATCH'||req.method==='DELETE')){if(!me)return json(res,401,{error:'يجب تسجيل الدخول أولًا'});let id=Number(m[1]),l=await get('SELECT * FROM listings WHERE id=? AND seller_id=?',[id,me.id]);if(!l)return json(res,404,{error:'الإعلان غير موجود أو لا تملكه'});if(req.method==='DELETE'){await run('DELETE FROM listings WHERE id=?',[id]);return json(res,200,{ok:true})}let b=await body(req),title=typeof b.title==='string'?b.title.trim():l.title,description=typeof b.description==='string'?b.description.trim():l.description,price=b.price===undefined?l.price:Number(b.price),status=['active','sold','hidden'].includes(b.status)?b.status:l.status,images=b.images===undefined?l.images:(Array.isArray(b.images)?JSON.stringify(b.images):'');if(title.length<3||title.length>70)return json(res,400,{error:'العنوان يجب أن يكون بين 3 و70 حرفًا'});if(description.length<3||description.length>3000)return json(res,400,{error:'الوصف غير صالح'});if(!Number.isFinite(price)||price<0)return json(res,400,{error:'السعر غير صالح'});if(images.length>8*1024*1024)return json(res,400,{error:'حجم الصور كبير جدًا'});await run('UPDATE listings SET title=?,description=?,price=?,status=?,images=? WHERE id=?',[title,description,price,status,images,id]);return json(res,200,listing(await get('SELECT * FROM listings WHERE id=?',[id])))}
if(req.method==='GET'&&(u.pathname==='/'||u.pathname==='/index.html')){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return fs.createReadStream(path.join(root,'index.html')).pipe(res)}
if(req.method==='GET'&&u.pathname==='/firestore.rules'){res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8'});return res.end(fs.readFileSync(path.join(root,'firestore.rules'),'utf8'))}
res.writeHead(404);res.end('Not found')}catch(e){console.error(e);json(res,500,{error:'??? ??? ????? ?? ??????'})}});
(async()=>{if(usePostgres){await pool.query(schema);await pool.query("ALTER TABLE listings ADD COLUMN IF NOT EXISTS images TEXT NOT NULL DEFAULT '[]'")}else{try{sqlite.exec("ALTER TABLE listings ADD COLUMN images TEXT NOT NULL DEFAULT '[]'")}catch(e){if(!String(e.message).toLowerCase().includes('duplicate column'))throw e}}server.listen(port,host,()=>console.log(`????? ???? ?????? ??? http://${host}:${port}`))})().catch(e=>{console.error(e);process.exitCode=1});
